### ISSUE TITLE
None verbose output

### ISSUE THREAD

**Issue by jurquiza** [EPCCed/pynmmso-examples#2]
Im trying it for optimising a very small model, in python3 in Jupyter lab but it would be great if I could make it less verbose now it prints every iteration 

Finished iteration 128, evaluations this iteration: 3, total evaluations: 499, number of swarms: 1
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
Finished iteration 129, evaluations this iteration: 4, total evaluations: 503, number of swarms: 1
Maximum number of evaluations reached.  Total evaluations: 503

**Comment by allyhume** [comment]
Hi Uriel,

The float stuff looks a little like a bug.   

Details about trace output can be found at: https://github.com/EPCCed/pynmmso/wiki/Using-the-listener-class#tracing-the-algorithms-progress

Are you adding a trace listener?  I would not expect you to get any output unless you specify a trace listener.  If you have added a trace listener and do don't want one then just remove the line that adds it.  If you want less detail then try making the level parameter lower (1 is the lowest).   If this does not do want you want then you can write your own Listener class to produce the exact level of trace that you wish, and add that.

But having said all that the float lines are worrying, that sounds like a debug line may have crept into the release.

Can you try playing with the listener funtionality and see if this fixes things and get back to me.

Cheers,

Ally

**Comment by jurquiza** [comment]
Hi Ally, 
Thanks for the promptly response I got the float message after removing the listener. 

I am trying to imitate you sbml example but with my model 


class SbmlModelProblem:
    def __init__(self, sbml, experimentData):
        self.sbml = sbml
        self.experimentData = experimentData
        self.rr = None
        
        
    def fitness(self,x):
        if self.rr is None:
            self.rr = roadrunner.RoadRunner(self.sbml)
        
        self.rr.resetToOrigin()
        
        self.rr.k1 = x[0]
        self.rr.k2 = x[1]
        self.rr.k3 = x[2]
        self.rr.k4 = x[3]
        self.rr.n1 = x[4]
        self.rr.n2 = x[5]
        self.rr.n3 = x[6]
        self.rr.m1 = x[7]
        self.rr.m2 = x[8]
        self.rr.m3 = x[9]
        self.rr.m4 = x[10]
        self.rr.m5 = x[11]
        self.rr.g1 = x[12]
        
        self.rr.timCourseSelections = ['time','cLUC']
        result = self.rr.simulate(0,96,97)
        
        sum_of_squares_error = float(np.sum(np.square(result[48:,1:])-self.experimentData))
        print(type(sum_of_squares_error))
        return -sum_of_squares_error

    def get_bounds(self):
        original_values = np.array([1,1,1,1,1,1,1,0.05,0.05,0.05,0.05,0.05,1])
        return 0.7 * original_values, 1.3*original_values
        
    def __getstate__(self):
    
        return{
            'sbml':self.sbml,
            'expData': self.experimentData
            
        }
    
    def __setstate__(self):
        self.sbml = state['sbml']
        self.experimentData = state['expData']
        self.rr = None
        
        
def main():
    
    UU2020_model = te.loadAntimonyModel('models/UU2020.1.txt')
    sbml = UU2020_model.getSBML()
    rr = roadrunner.RoadRunner(sbml)
    rr.resetToOrigin()
    rr.timeCourseSelections = ['time','cLUC']
    fake_experiment_data = rr.simulate(0,96,97)
    
    fake_experiment_data = np.array(fake_experiment_data[48:,1:])
    
    nmmso = Nmmso(UniformRangeProblem(SbmlModelProblem(sbml, fake_experiment_data)), 10)
    
    my_result = nmmso.run(500)
    
    
    #for mode_result in my_result:
    #    print("Mode at {} has value {}".format(mode_result.location, mode_result.value))
    
    return(my_result)
        
if __name__ == "__main__":
    main()

**Comment by jurquiza** [comment]
I just realised I had a parenthesis typo, and which was causing trouble so I was printing out the type of the variable. Sorry, it is now solved !!! I think I am good to go and ill be working with it for some time thanks Ally

**Comment by allyhume** [comment]
Excellent.  Thanks for letting me know.  I'll close this issue.
